# Generated by Django 2.1.7 on 2019-03-21 09:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_remove_post_publish'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 21, 9, 22, 27, 473610, tzinfo=utc)),
        ),
    ]
